[project]
name = "decrypt-otpauth-files"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "bpylist2>=4.1.1",
    "click>=8.3.1",
    "pycryptodome>=3.23.0",
    "pyqrcode>=1.2.1",
    "rncryptor>=3.3.0",
]
